### ISSUE TITLE
FormattedNumber from react-intl uses a custom style props

### ISSUE THREAD

**Issue by PSniezak** [ornikar/eslint-configs#15]
## Problem

The `FormattedNumber` component from `react-intl` uses a `style` prop (from `Intl.NumberFormat`) to specify the number's unit. It conflicts with the rule `react/style-prop-object`.

## Example

[Learner-webapp](https://github.com/ornikar/learner-webapp/blob/546c9f4cb89351b499afd4871f4ee5a7f2a42c17/src/sections/driving/onboarding/pages/DrivingInstructor/index.tsx#L65)

**Comment by christophehurpeau** [comment]
See documentation: https://ornikar.atlassian.net/wiki/spaces/TECH/pages/982712688/Internationalisation+Guidelines+react-intl+and+more#Distance `format` prop should be used instead of `style`.
